swagger: "2.0"
info:
  version: "0.2"
  title: swagger-express-api-splitter
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
- name: "Users"
  description: "Your users"
- name: "Stores"
  description: "Your company stores"
paths: